### ISSUE TITLE
ADAQ Control, Readout, ASIM Readout Makefiles

### ISSUE THREAD

**Issue by tdmacd87** [zach-hartwig/ADAQ#1]
$ADAQHOME is not defined within the ADAQ Control Makefile, had to be declared manually.

The ReadoutDict.cc files in both ADAQReadout/build and ASIMReadout/build contain a couple of include statements at the top:
# include <include/someFile.hh>

which were throwing fatal errors when using make. Needed to change to:
# include <../include/someFile.hh>

to point to the correct directories

**Comment by zach-hartwig** [comment]
The ADAQHOME environmental variable is set by the 'setup.sh' script, which can be found in the $ADAQREPO/scripts directory. As noted in the installation directions in Readme.md, this script should be sourced in your terminal session to correctly setup the environmental variables, including ADAQHOME. On Linux, this is most easily done in your .bashrc file. Note that you must open a new terminal for the settings to take effect.

The issue with generating the ROOT dictionaries occurs because the ADAQHOME environmental variable is not set correctly when you attempt to build the {ADAQ,ASIM}Readout libraries. The absolute path to the headers must be defined so that they may be located correctly within the build system.

Let me know if you continue to have issues, particularly if you are trying this on a non-Linux platform (probably MacOS). It would be interesting for me to know if it can be built on MacOS and/or what changes may need to be made to the build structure.

**Comment by tdmacd87** [comment]
Gotcha,  I see it now. I had issues building the libraries, was just lost because the line in the readme with the setup script is after the build instructions. Have it working though, was installing on Ubuntu. 

Cheers

**Comment by zach-hartwig** [comment]
Excellent. Thanks for the feedback on the confusing order of the build instructions. I've updated the Readme.md file in the master branch with much clearer and properly ordered instructions to ensure the user sources the setup.sh script _before_ attempting to build the libraries. Closing this issue.
